import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val mnemonik: String = "com.github.aballano:MnemoniK:_"

    public const val fuel: String = "com.github.kittinunf.fuel:fuel:_"

    public const val generex: String = "com.github.mifmif:generex:_"

    public const val guava: String = "com.google.guava:guava:_"

    public const val com_google_zxing_core: String = "com.google.zxing:core:_"

    public const val javase: String = "com.google.zxing:javase:_"

    public const val discretemathtoolkit: String = "com.marcinmoskala:DiscreteMathToolkit:_"

    public const val mockito_kotlin: String = "com.nhaarman:mockito-kotlin:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val arrow_core: String = "io.arrow-kt:arrow-core:_"

    public const val kotlin_logging: String = "io.github.microutils:kotlin-logging:_"

    public const val z3_turnkey: String = "io.github.tudo-aqua:z3-turnkey:_"

    public const val junit: String = "junit:junit:_"

    public const val jna: String = "net.java.dev.jna:jna:_"

    public const val jna_platform: String = "net.java.dev.jna:jna-platform:_"

    public const val tess4j: String = "net.sourceforge.tess4j:tess4j:_"

    public const val commons_text: String = "org.apache.commons:commons-text:_"

    public const val bcprov_jdk15on: String = "org.bouncycastle:bcprov-jdk15on:_"

    public const val zircon_core: String = "org.hexworks.zircon:zircon.core:_"

    public const val zircon_jvm: String = "org.hexworks.zircon:zircon.jvm:_"

    public const val zircon_jvm_swing: String = "org.hexworks.zircon:zircon.jvm.swing:_"

    public const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_serialization_json_jvm: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:_"

    public const val jgrapht_core: String = "org.jgrapht:jgrapht-core:_"
}
